# Generated by Django 4.2.7 on 2025-12-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_only',
            field=models.BooleanField(default=False, verbose_name='Show online profiles only'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_only',
            field=models.BooleanField(default=False, verbose_name='Show verified profiles only'),
        ),
    ]
