# Generated by Django 4.2.7 on 2026-01-19 23:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_fix_genders_sought"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="genders_sought",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("male", "Male"),
                        ("female", "Female"),
                        ("non_binary", "Non-binary"),
                        ("trans_male", "Trans male"),
                        ("trans_female", "Trans female"),
                        ("other", "Other"),
                        ("prefer_not_to_say", "Prefer not to say"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                help_text="List of genders this profile is interested in. Empty list means open to all genders.",
                size=None,
                verbose_name="Gender preferences",
            ),
        ),
    ]
