# Generated by Django 5.2.4 on 2026-08-16 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_genders_sought'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('grace_period_hours', models.PositiveIntegerField(default=72, verbose_name='Grace period (hours)')),
                ('confirmation_token', models.CharField(blank=True, max_length=64, verbose_name='Confirmation token')),
                ('cancellation_token', models.CharField(blank=True, max_length=64, verbose_name='Cancellation token')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_deletion_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'account_deletion_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='account_del_user_id_85393b_idx'), models.Index(fields=['confirmation_token'], name='account_del_confirm_6a5fb8_idx'), models.Index(fields=['cancellation_token'], name='account_del_cancell_fbf168_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Download link expires at')),
                ('download_url', models.URLField(blank=True, max_length=1000, verbose_name='Signed download URL')),
                ('error_log', models.TextField(blank=True, verbose_name='Error log')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'data_export_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='data_export_user_id_58dcab_idx'), models.Index(fields=['expires_at'], name='data_export_expires_693dcb_idx')],
            },
        ),
    ]
