# Generated by Django 4.2.7 on 2026-09-22 13:55

import csv
import json
from pathlib import Path

from django.db import migrations, models
import django.db.models.deletion


def seed_geonames_countries(apps, schema_editor):
    """Seed the checked-in GeoNames country catalogue without network I/O."""
    GeoCountry = apps.get_model('profiles', 'GeoCountry')
    source = Path(__file__).resolve().parent.parent / 'data' / 'countryInfo.txt'
    french_source = Path(__file__).resolve().parent.parent / 'data' / 'territories_fr.json'
    if not source.exists():
        return
    french_names = {}
    if french_source.exists():
        with french_source.open(encoding='utf-8') as stream:
            french_names = (
                json.load(stream).get('main', {}).get('fr', {})
                .get('localeDisplayNames', {}).get('territories', {})
            )
    with source.open(encoding='utf-8') as stream:
        for row in csv.reader(stream, delimiter='\t'):
            if not row or row[0].startswith('#') or len(row) < 17:
                continue
            code = row[0].strip().upper()
            if len(code) != 2:
                continue
            GeoCountry.objects.update_or_create(
                code=code,
                defaults={
                    'geonames_id': int(row[16]) if row[16].isdigit() else None,
                    'name': row[4].strip(),
                    'name_fr': french_names.get(code, ''),
                    'catalog_version': 'geonames-2026-09',
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_preferred_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCountry',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('geonames_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_fr', models.CharField(blank=True, max_length=120)),
                ('catalog_version', models.CharField(default='geonames-v1', max_length=32)),
            ],
            options={
                'db_table': 'geo_countries',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_geonames_countries, migrations.RunPython.noop),
        migrations.AddField(
            model_name='profile',
            name='location_accuracy_m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Location accuracy in metres'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_enabled',
            field=models.BooleanField(default=True, verbose_name='Use device location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_mode',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=12, verbose_name='Location mode'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Location updated at'),
        ),
        migrations.CreateModel(
            name='GeoCity',
            fields=[
                ('geonames_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('ascii_name', models.CharField(blank=True, max_length=180)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('population', models.PositiveBigIntegerField(default=0)),
                ('catalog_version', models.CharField(default='geonames-v1', max_length=32)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='profiles.geocountry')),
            ],
            options={
                'db_table': 'geo_cities',
                'ordering': ['-population', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='geo_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profiles.geocity', verbose_name='Catalog city'),
        ),
        migrations.AddIndex(
            model_name='geocity',
            index=models.Index(fields=['country', 'name'], name='geo_cities_country_700a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='geocity',
            index=models.Index(fields=['country', 'ascii_name'], name='geo_cities_country_a11a31_idx'),
        ),
    ]
