# Generated by Django 5.2.4 on 2026-09-26 14:10

import django.contrib.postgres.fields
from django.db import migrations, models
import unicodedata


def _search(value):
    normalized = unicodedata.normalize("NFKD", value or "")
    return "".join(char for char in normalized if not unicodedata.combining(char)).casefold().strip()


def normalize_existing_profiles_and_catalog(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    GeoCountry = apps.get_model("profiles", "GeoCountry")
    GeoCity = apps.get_model("profiles", "GeoCity")
    valid = {"male", "female"}
    relation_map = {
        "friendship": "friendship", "long_term": "long_term",
        "short_term": "short_term", "casual": "casual",
        "serious": "long_term", "serious_relationship": "long_term",
        "short": "short_term", "casual_dating": "casual",
    }
    for profile in Profile.objects.all().iterator():
        fields = []
        if profile.gender not in valid:
            profile.legacy_gender = profile.gender or ""
            profile.gender = ""
            profile.gender_confirmation_required = True
            profile.allow_profile_in_discovery = False
            fields += ["legacy_gender", "gender", "gender_confirmation_required", "allow_profile_in_discovery"]
        sought = []
        for value in profile.genders_sought or []:
            if value in valid and value not in sought:
                sought.append(value)
        # Two legacy selected values are semantically "everyone" now that
        # Discovery exposes a single-choice control.
        if len(sought) > 1:
            sought = []
        if sought != (profile.genders_sought or []):
            profile.genders_sought = sought
            fields.append("genders_sought")
        relations = []
        for value in profile.relationship_types_sought or []:
            normalized = relation_map.get(value)
            if normalized and normalized not in relations:
                relations.append(normalized)
        if relations != (profile.relationship_types_sought or []):
            profile.relationship_types_sought = relations
            fields.append("relationship_types_sought")
        if fields:
            profile.save(update_fields=fields)
    for country in GeoCountry.objects.all().iterator():
        country.search_name = _search(f"{country.code} {country.name} {country.name_fr}")
        country.save(update_fields=["search_name"])
    for city in GeoCity.objects.all().iterator():
        city.search_name = _search(f"{city.name} {city.ascii_name}")
        city.save(update_fields=["search_name"])


def reverse_normalize_existing_profiles_and_catalog(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    for profile in Profile.objects.exclude(legacy_gender="").filter(gender="").iterator():
        profile.gender = profile.legacy_gender
        profile.gender_confirmation_required = False
        profile.save(update_fields=["gender", "gender_confirmation_required"])



class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_geo_catalog_and_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCatalogRelease',
            fields=[
                ('catalog_version', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64)),
                ('city_count', models.PositiveIntegerField()),
                ('attribution_url', models.URLField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geo_catalog_releases',
            },
        ),
        migrations.AddField(
            model_name='geocity',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='geocountry',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_confirmation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='legacy_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genders_sought',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20), blank=True, default=list, help_text='List of genders this profile is interested in. Empty list means open to all genders.', size=None, verbose_name='Gender preferences'),
        ),
        migrations.RunPython(normalize_existing_profiles_and_catalog, reverse_normalize_existing_profiles_and_catalog),
    ]
