# Generated by Django 5.2.4 on 2026-10-01 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_normalize_sought_gender_single_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('pending_id', 'Pending identity document'), ('pending_medical', 'Pending medical document'), ('pending_selfie', 'Pending selfie'), ('pending_review', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='not_started', max_length=20)),
                ('origin', models.CharField(choices=[('user_start', 'User start'), ('legacy_projection', 'Legacy projection')], default='user_start', max_length=24)),
                ('is_open', models.BooleanField(default=True, help_text='Only one open KYC attempt is allowed per user.')),
                ('consent_version', models.CharField(blank=True, max_length=80)),
                ('rejection_reason_code', models.CharField(blank=True, max_length=80)),
                ('challenge_hash', models.CharField(blank=True, max_length=256)),
                ('challenge_nonce', models.CharField(blank=True, max_length=64)),
                ('challenge_idempotency_key', models.CharField(blank=True, max_length=128)),
                ('challenge_expires_at', models.DateTimeField(blank=True, null=True)),
                ('challenge_used_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KycAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('event_type', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_audit_events', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='profiles.kycattempt')),
            ],
            options={
                'db_table': 'kyc_audit_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('identity_document', 'Identity document'), ('medical_document', 'Medical document'), ('selfie_with_code', 'Selfie with challenge')], max_length=32)),
                ('opaque_storage_key', models.CharField(max_length=255, unique=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('detected_mime_type', models.CharField(blank=True, max_length=100)),
                ('scan_status', models.CharField(choices=[('issued', 'Issued'), ('uploaded', 'Uploaded'), ('scanning', 'Scanning'), ('quarantined', 'Quarantined'), ('accepted', 'Accepted'), ('purged', 'Purged')], db_index=True, default='issued', max_length=16)),
                ('purge_after', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.kycattempt')),
            ],
            options={
                'db_table': 'kyc_documents',
            },
        ),
        migrations.CreateModel(
            name='KycUploadIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('identity_document', 'Identity document'), ('medical_document', 'Medical document'), ('selfie_with_code', 'Selfie with challenge')], max_length=32)),
                ('declared_mime_type', models.CharField(max_length=100)),
                ('declared_size_bytes', models.PositiveBigIntegerField()),
                ('declared_sha256', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('opaque_object_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('consumed', 'Consumed'), ('expired', 'Expired')], db_index=True, default='issued', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_intents', to='profiles.kycattempt')),
            ],
            options={
                'db_table': 'kyc_upload_intents',
            },
        ),
        migrations.AddIndex(
            model_name='kycattempt',
            index=models.Index(fields=['user', 'status'], name='kyc_attempt_user_id_69c843_idx'),
        ),
        migrations.AddIndex(
            model_name='kycattempt',
            index=models.Index(fields=['status', 'expires_at'], name='kyc_attempt_status_cb12b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='kycattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('user',), name='profiles_one_open_kyc_attempt_per_user'),
        ),
        migrations.AddIndex(
            model_name='kycauditevent',
            index=models.Index(fields=['attempt', 'created_at'], name='kyc_audit_e_attempt_04b6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='kycauditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='kyc_audit_e_event_t_9a7d34_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['attempt', 'scan_status'], name='kyc_documen_attempt_0b98aa_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['purge_after'], name='kyc_documen_purge_a_1e6428_idx'),
        ),
        migrations.AddConstraint(
            model_name='kycdocument',
            constraint=models.UniqueConstraint(fields=('attempt', 'document_type'), name='profiles_one_kyc_document_type_per_attempt'),
        ),
        migrations.AddIndex(
            model_name='kycuploadintent',
            index=models.Index(fields=['attempt', 'document_type'], name='kyc_upload__attempt_81d258_idx'),
        ),
        migrations.AddIndex(
            model_name='kycuploadintent',
            index=models.Index(fields=['status', 'expires_at'], name='kyc_upload__status_0857a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='kycuploadintent',
            constraint=models.UniqueConstraint(fields=('attempt', 'idempotency_key'), name='profiles_kyc_upload_intent_idempotency'),
        ),
    ]
