# Generated by Django 5.2.4 on 2026-10-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_create_legacy_kyc_reverification_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='deletion_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='next_purge_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='purge_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='quarantine_reason_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='scan_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='scan_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='scan_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycuploadintent',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_intents', to='profiles.kycdocument'),
        ),
        migrations.AddField(
            model_name='kycuploadintent',
            name='scan_enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycuploadintent',
            name='upload_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='legacy_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='private_migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='storage_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='storage_state',
            field=models.CharField(choices=[('legacy_public', 'Legacy public object'), ('migration_copied', 'Private copy awaiting legacy deletion'), ('private', 'Private object'), ('migration_failed', 'Private migration failed')], db_index=True, default='legacy_public', max_length=24),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='thumbnail_storage_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Photo URL'),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Thumbnail URL'),
        ),
    ]
