# Generated by Django 5.2.4 on 2026-10-02 08:53

from django.db import migrations, models
from urllib.parse import unquote, urlparse


def legacy_profile_path_for_owner(value, owner_id):
    """Match exactly the namespace emitted by the historical photo writer."""
    if not value:
        return None
    parsed = urlparse(value)
    path = unquote(parsed.path or value).lstrip('/')
    if parsed.netloc == 'storage.googleapis.com' and '/' in path:
        path = path.split('/', 1)[1]
    elif parsed.netloc.endswith('firebasestorage.googleapis.com') and '/o/' in path:
        path = path.split('/o/', 1)[1]
    expected_prefix = f'profiles/{owner_id}/'
    return path if path.startswith(expected_prefix) else None


def mark_preexisting_legacy_sources(apps, schema_editor):
    """Classify only a complete, owner-bound pre-cutover photo pair."""
    ProfilePhoto = apps.get_model('profiles', 'ProfilePhoto')
    for photo in ProfilePhoto.objects.select_related('profile').iterator():
        owner_id = photo.profile.user_id
        verified = bool(
            legacy_profile_path_for_owner(photo.photo_url, owner_id)
            and legacy_profile_path_for_owner(photo.thumbnail_url, owner_id)
        )
        if photo.legacy_source_verified != verified:
            photo.legacy_source_verified = verified
            photo.save(update_fields=['legacy_source_verified'])


def unmark_legacy_sources(apps, schema_editor):
    ProfilePhoto = apps.get_model('profiles', 'ProfilePhoto')
    ProfilePhoto.objects.update(legacy_source_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_phase2_private_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='legacy_source_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_preexisting_legacy_sources, unmark_legacy_sources),
    ]
