# Generated by Django 4.2.7 on 2026-08-24 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Contenu inapproprié'), ('harassment', 'Harcèlement'), ('scam', 'Arnaque'), ('other', 'Autre')], max_length=20, verbose_name='Motif')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', 'En cours de traitement'), ('resolved', 'Résolu'), ('dismissed', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notes de résolution')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur signalé')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Signaleur')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reporter', '-created_at'], name='authenticat_reporte_1ecc55_idx'), models.Index(fields=['reported_user', '-created_at'], name='authenticat_reporte_2116d8_idx'), models.Index(fields=['status'], name='authenticat_status_2c0608_idx')],
            },
        ),
    ]
