"""Private, opaque object storage for KYC evidence and profile media.

This module deliberately never makes a blob public and never persists a signed
URL.  Production uses separate GCS buckets with UBLA and bucket-default CMEK;
the memory backend exists only for isolated tests and local development.
"""

from __future__ import annotations

import hashlib
import re
import secrets
import subprocess
import warnings
from dataclasses import dataclass
from io import BytesIO
from urllib.parse import unquote, urlparse

from django.conf import settings
from django.utils import timezone
from PIL import Image, UnidentifiedImageError


class PrivateStorageError(RuntimeError):
    """Base error that never embeds an object name, URL or document content."""


class PrivateStorageUnavailable(PrivateStorageError):
    """Storage or its required security configuration is unavailable."""


class PrivateObjectNotFound(PrivateStorageError):
    """The expected private object does not exist."""


class PrivateObjectIntegrityError(PrivateStorageError):
    """Uploaded bytes do not meet the declared technical contract."""


class PrivateObjectMalwareDetected(PrivateStorageError):
    """The configured antivirus scanner rejected the object."""


@dataclass(frozen=True)
class PrivateObjectMetadata:
    size_bytes: int
    content_type: str


_MEMORY_OBJECTS: dict[tuple[str, str], tuple[bytes, str]] = {}


_PRIVATE_KEY_PREFIXES = {
    'kyc': 'kyc/quarantine/',
    'profile': 'profile-media/private/',
}
_PRIVATE_KEY_TOKEN_RE = re.compile(r'^[A-Za-z0-9_-]{32,128}$')
_OBJECT_ACCESS_ROLES = frozenset({
    # Modern bucket-scoped roles that can read, write or administer objects.
    'roles/storage.admin',
    'roles/storage.objectAdmin',
    'roles/storage.objectCreator',
    'roles/storage.objectUser',
    'roles/storage.objectViewer',
    # Legacy roles and basic roles remain effective if inherited into a bucket
    # policy, so a private KYC bucket must reject them as well.
    'roles/storage.legacyBucketOwner',
    'roles/storage.legacyBucketReader',
    'roles/storage.legacyObjectOwner',
    'roles/storage.legacyObjectReader',
    'roles/storage.legacyObjectWriter',
    'roles/viewer',
    'roles/editor',
    'roles/owner',
})


def _is_local_safe_mode() -> bool:
    return bool(getattr(settings, 'TESTING', False) or settings.DEBUG)


def _scope_settings(scope: str) -> tuple[str, str, str]:
    if scope == 'kyc':
        return (
            settings.KYC_STORAGE_BACKEND,
            settings.KYC_STORAGE_BUCKET,
            settings.KYC_STORAGE_KMS_KEY,
        )
    if scope == 'profile':
        return (
            settings.PROFILE_MEDIA_STORAGE_BACKEND,
            settings.PROFILE_MEDIA_PRIVATE_BUCKET,
            settings.PROFILE_MEDIA_KMS_KEY,
        )
    raise ValueError('Unknown private-storage scope')


def _require_private_key(scope: str, key: str) -> None:
    """Reject a malformed/cross-scope key before an object-store operation.

    Keys are generated by :meth:`PrivateObjectStorage.new_key`.  Checking the
    namespace again at every storage boundary ensures a corrupt database row
    cannot turn a cleanup or media read into an operation on another object's
    name.  The exception deliberately contains neither the key nor its value.
    """
    prefix = _PRIVATE_KEY_PREFIXES.get(scope)
    if not prefix or not isinstance(key, str) or not key.startswith(prefix):
        raise PrivateObjectIntegrityError()
    token = key[len(prefix):]
    if not _PRIVATE_KEY_TOKEN_RE.fullmatch(token):
        raise PrivateObjectIntegrityError()


def private_storage_configuration_errors(scope: str) -> list[str]:
    """Return safe configuration codes without contacting object storage."""
    backend, bucket, kms_key = _scope_settings(scope)
    if backend == 'memory':
        return [] if _is_local_safe_mode() else ['memory_backend_forbidden']
    if backend != 'gcs':
        return ['unsupported_backend']
    missing = []
    if not bucket:
        missing.append('bucket_missing')
    if not kms_key:
        missing.append('kms_key_missing')
    if not settings.PRIVATE_STORAGE_RUNTIME_SERVICE_ACCOUNT:
        missing.append('runtime_service_account_missing')
    if scope == 'profile' and settings.PROFILE_MEDIA_MAX_IMAGE_PIXELS <= 0:
        missing.append('profile_image_limit_invalid')
    if scope == 'profile' and settings.PROFILE_MEDIA_MAX_UPLOAD_BYTES <= 0:
        missing.append('profile_media_byte_limit_invalid')
    other_bucket = (
        settings.PROFILE_MEDIA_PRIVATE_BUCKET
        if scope == 'kyc' else settings.KYC_STORAGE_BUCKET
    )
    other_kms_key = (
        settings.PROFILE_MEDIA_KMS_KEY
        if scope == 'kyc' else settings.KYC_STORAGE_KMS_KEY
    )
    if bucket and bucket == other_bucket:
        missing.append('bucket_not_distinct')
    if kms_key and kms_key == other_kms_key:
        missing.append('kms_key_not_distinct')
    if scope == 'kyc' and settings.KYC_DOCUMENT_RETENTION_DAYS <= 0:
        missing.append('retention_not_approved')
    if scope == 'kyc':
        if settings.KYC_MAX_IMAGE_PIXELS <= 0:
            missing.append('image_pixel_limit_invalid')
        if settings.KYC_MAX_PDF_PAGES <= 0:
            missing.append('pdf_page_limit_invalid')
        if settings.KYC_MAX_PDF_OBJECTS <= 0:
            missing.append('pdf_object_limit_invalid')
        if settings.KYC_SCAN_TIMEOUT_SECONDS <= 0:
            missing.append('scan_timeout_invalid')
        if not settings.KYC_CLAMAV_BINARY:
            missing.append('clamav_binary_missing')
        if settings.KYC_STORAGE_UPLOAD_TTL_SECONDS <= 0:
            missing.append('upload_ttl_invalid')
        if settings.KYC_QUARANTINE_RETENTION_HOURS <= 0:
            missing.append('quarantine_retention_invalid')
        if settings.KYC_ANTIVIRUS_BACKEND == 'test' and not _is_local_safe_mode():
            missing.append('test_antivirus_forbidden')
        elif settings.KYC_ANTIVIRUS_BACKEND not in {'clamav-cli', 'test'}:
            missing.append('antivirus_not_configured')
    return missing


class PrivateObjectStorage:
    """Storage adapter with no public-object operation in its API."""

    def _bucket(self, scope: str):
        errors = private_storage_configuration_errors(scope)
        if errors:
            raise PrivateStorageUnavailable()
        backend, bucket_name, _ = _scope_settings(scope)
        if backend != 'gcs':
            return None
        try:
            # Import lazily: tests and development-memory flows must not require
            # cloud credentials or initialise a production Firebase client.
            from firebase_admin import storage as firebase_storage
            from hivmeet_backend.firebase_service import firebase_service

            _ = firebase_service.bucket
            return firebase_storage.bucket(name=bucket_name)
        except Exception:  # provider detail must not leave this boundary
            raise PrivateStorageUnavailable() from None

    def new_key(self, scope: str) -> str:
        """Return a random key with no account, e-mail or document type segment."""
        try:
            prefix = _PRIVATE_KEY_PREFIXES[scope]
        except KeyError:
            raise ValueError('Unknown private-storage scope') from None
        return f'{prefix}{secrets.token_urlsafe(32)}'

    def issue_upload_url(self, *, key: str, content_type: str, content_length: int,
                         expires_at):
        """Issue one constrained V4 PUT URL; callers never store its value.

        ``Content-Length`` is a signed V4 header: Cloud Storage rejects a PUT
        that omits it or whose byte count differs from the server-declared
        size. The post-upload validation remains mandatory defence in depth.
        """
        _require_private_key('kyc', key)
        if not isinstance(content_length, int) or content_length <= 0:
            raise PrivateObjectIntegrityError()
        backend, bucket_name, _ = _scope_settings('kyc')
        if backend == 'memory':
            if not _is_local_safe_mode():
                raise PrivateStorageUnavailable()
            # Non-routable URL for hermetic tests only. It is never persisted.
            return f'https://uploads.invalid/{bucket_name}/{key}'
        bucket = self._bucket('kyc')
        try:
            return bucket.blob(key).generate_signed_url(
                version='v4',
                expiration=expires_at,
                method='PUT',
                content_type=content_type,
                headers={'Content-Length': str(content_length)},
                query_parameters={'ifGenerationMatch': '0'},
            )
        except Exception:
            raise PrivateStorageUnavailable() from None

    def put_bytes(self, *, scope: str, key: str, data: bytes, content_type: str):
        """Write private data without ACL mutation or public URL generation."""
        _require_private_key(scope, key)
        backend, bucket_name, _ = _scope_settings(scope)
        if backend == 'memory':
            if not _is_local_safe_mode():
                raise PrivateStorageUnavailable()
            _MEMORY_OBJECTS[(bucket_name, key)] = (bytes(data), content_type)
            return
        bucket = self._bucket(scope)
        try:
            blob = bucket.blob(key)
            blob.cache_control = 'private, no-store, max-age=0'
            blob.upload_from_string(
                data,
                content_type=content_type,
                if_generation_match=0,
            )
        except Exception:
            raise PrivateStorageUnavailable() from None

    def metadata(self, *, scope: str, key: str) -> PrivateObjectMetadata:
        _require_private_key(scope, key)
        backend, bucket_name, _ = _scope_settings(scope)
        if backend == 'memory':
            try:
                data, content_type = _MEMORY_OBJECTS[(bucket_name, key)]
            except KeyError:
                raise PrivateObjectNotFound() from None
            return PrivateObjectMetadata(len(data), content_type)
        bucket = self._bucket(scope)
        try:
            blob = bucket.blob(key)
            blob.reload()
            return PrivateObjectMetadata(int(blob.size or 0), blob.content_type or '')
        except Exception as exc:
            if exc.__class__.__name__ == 'NotFound':
                raise PrivateObjectNotFound() from None
            raise PrivateStorageUnavailable() from None

    def download(self, *, scope: str, key: str) -> bytes:
        _require_private_key(scope, key)
        backend, bucket_name, _ = _scope_settings(scope)
        if backend == 'memory':
            try:
                return _MEMORY_OBJECTS[(bucket_name, key)][0]
            except KeyError:
                raise PrivateObjectNotFound() from None
        bucket = self._bucket(scope)
        try:
            return bucket.blob(key).download_as_bytes()
        except Exception as exc:
            if exc.__class__.__name__ == 'NotFound':
                raise PrivateObjectNotFound() from None
            raise PrivateStorageUnavailable() from None

    def delete(self, *, scope: str, key: str) -> bool:
        """Delete an object and return whether absence is now verified."""
        _require_private_key(scope, key)
        backend, bucket_name, _ = _scope_settings(scope)
        if backend == 'memory':
            _MEMORY_OBJECTS.pop((bucket_name, key), None)
            return (bucket_name, key) not in _MEMORY_OBJECTS
        bucket = self._bucket(scope)
        try:
            blob = bucket.blob(key)
            blob.delete()
            return not blob.exists()
        except Exception as exc:
            if exc.__class__.__name__ == 'NotFound':
                return True
            raise PrivateStorageUnavailable() from None

    def verify_bucket_policy(self, scope: str) -> list[str]:
        """Check UBLA, CMEK, CORS and the expected private IAM grant."""
        backend, _, expected_kms_key = _scope_settings(scope)
        if backend == 'memory':
            return [] if _is_local_safe_mode() else ['memory_backend_forbidden']
        bucket = self._bucket(scope)
        errors = []
        try:
            bucket.reload()
            iam_configuration = bucket.iam_configuration
            ubla = getattr(iam_configuration, 'uniform_bucket_level_access_enabled', False)
            if not ubla:
                errors.append('ubla_disabled')
            if str(getattr(iam_configuration, 'public_access_prevention', '')).lower() != 'enforced':
                errors.append('public_access_prevention_not_enforced')
            if bucket.default_kms_key_name != expected_kms_key:
                errors.append('bucket_cmek_mismatch')
            cors_rules = bucket.cors or []
            if scope == 'kyc':
                if not cors_rules:
                    errors.append('cors_missing')
                for rule in cors_rules:
                    methods = {method.upper() for method in rule.get('method', ())}
                    origins = set(rule.get('origin', ()))
                    response_headers = {
                        header.lower()
                        for header in rule.get(
                            'responseHeader', rule.get('response_header', ()),
                        )
                    }
                    if 'PUT' not in methods:
                        errors.append('cors_required_method_missing')
                        break
                    if methods - {'PUT'}:
                        errors.append('cors_excessive_method')
                        break
                    if not origins:
                        errors.append('cors_origin_missing')
                        break
                    if '*' in origins:
                        errors.append('cors_wildcard_origin')
                        break
                    if response_headers - {'content-type', 'x-goog-generation'}:
                        errors.append('cors_excessive_response_header')
                        break
            elif cors_rules:
                errors.append('cors_direct_read_not_allowed')
            policy = bucket.get_iam_policy(requested_policy_version=3)
            bindings = getattr(policy, 'bindings', ())
            binding_values = [
                (
                    binding.get('role', '') if isinstance(binding, dict) else getattr(binding, 'role', ''),
                    tuple((
                        binding.get('members', ()) if isinstance(binding, dict)
                        else getattr(binding, 'members', ())
                    ) or ()),
                )
                for binding in bindings
            ]
            if any(
                member in {'allUsers', 'allAuthenticatedUsers'}
                for _, members in binding_values
                for member in members
            ):
                errors.append('public_iam_binding')
            expected_runtime_member = (
                f'serviceAccount:{settings.PRIVATE_STORAGE_RUNTIME_SERVICE_ACCOUNT}'
            )
            has_runtime_object_admin = any(
                role == 'roles/storage.objectAdmin' and expected_runtime_member in members
                for role, members in binding_values
            )
            if not has_runtime_object_admin:
                errors.append('runtime_object_admin_missing')
            if any(
                role in _OBJECT_ACCESS_ROLES and member != expected_runtime_member
                for role, members in binding_values
                for member in members
            ):
                # Return only a stable code: policy principals are operational
                # identifiers and must not leak through command output.
                errors.append('unexpected_object_access_binding')
        except Exception:
            raise PrivateStorageUnavailable() from None
        return errors


def canonical_mime_type(value: str) -> str:
    return 'image/jpeg' if value == 'image/jpg' else value.lower().strip()


def detect_binary_mime_type(data: bytes) -> str:
    if data.startswith(b'\xff\xd8\xff'):
        return 'image/jpeg'
    if data.startswith(b'\x89PNG\r\n\x1a\n'):
        return 'image/png'
    if data.startswith(b'%PDF-'):
        return 'application/pdf'
    raise PrivateObjectIntegrityError()


def validate_document_binary(*, data: bytes, expected_mime_type: str) -> str:
    """Validate signature and a bounded structural parse of an upload."""
    detected = detect_binary_mime_type(data)
    if detected != canonical_mime_type(expected_mime_type):
        raise PrivateObjectIntegrityError()
    if detected.startswith('image/'):
        previous_limit = Image.MAX_IMAGE_PIXELS
        Image.MAX_IMAGE_PIXELS = settings.KYC_MAX_IMAGE_PIXELS
        try:
            with warnings.catch_warnings():
                warnings.simplefilter('error', Image.DecompressionBombWarning)
                with Image.open(BytesIO(data)) as image:
                    image.verify()
                with Image.open(BytesIO(data)) as image:
                    image.load()
                    if image.width * image.height > settings.KYC_MAX_IMAGE_PIXELS:
                        raise PrivateObjectIntegrityError()
        except (
            UnidentifiedImageError,
            OSError,
            ValueError,
            Image.DecompressionBombError,
            Image.DecompressionBombWarning,
        ):
            raise PrivateObjectIntegrityError() from None
        finally:
            Image.MAX_IMAGE_PIXELS = previous_limit
    else:
        try:
            from pypdf import PdfReader

            reader = PdfReader(BytesIO(data), strict=True)
            page_count = len(reader.pages)
            indirect_object_count = sum(
                len(entries) for entries in reader.xref.values()
            ) + len(getattr(reader, 'xref_objStm', {}))
            if (
                reader.is_encrypted
                or page_count < 1
                or page_count > settings.KYC_MAX_PDF_PAGES
                or indirect_object_count > settings.KYC_MAX_PDF_OBJECTS
            ):
                raise PrivateObjectIntegrityError()
        except PrivateObjectIntegrityError:
            raise
        except Exception:
            raise PrivateObjectIntegrityError() from None
    return detected


def scan_antivirus(data: bytes):
    """Run the configured scanner; production never treats a missing scanner as clean."""
    backend = settings.KYC_ANTIVIRUS_BACKEND
    if backend == 'test' and _is_local_safe_mode():
        return
    if backend != 'clamav-cli':
        raise PrivateStorageUnavailable()
    try:
        result = subprocess.run(
            [settings.KYC_CLAMAV_BINARY, '--no-summary', '-'],
            input=data,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=settings.KYC_SCAN_TIMEOUT_SECONDS,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        raise PrivateStorageUnavailable() from None
    if result.returncode == 1:
        raise PrivateObjectMalwareDetected()
    if result.returncode != 0:
        raise PrivateStorageUnavailable()


def legacy_profile_object_path(value: str, *, owner_id=None) -> str | None:
    """Accept a legacy path only when it belongs to its profile owner.

    The legacy Firebase bucket is shared.  A row marker alone is insufficient
    authority to copy or delete an object: the historical writer always used
    ``profiles/<user UUID>/...``, so every cutover operation must prove that
    namespace before touching the configured bucket.
    """
    if not value:
        return None
    parsed = urlparse(value)
    path = unquote(parsed.path or value).lstrip('/')
    if parsed.netloc == 'storage.googleapis.com' and '/' in path:
        path = path.split('/', 1)[1]
    elif parsed.netloc.endswith('firebasestorage.googleapis.com') and '/o/' in path:
        path = path.split('/o/', 1)[1]
    if not path.startswith('profiles/'):
        return None
    if owner_id is not None and not path.startswith(f'profiles/{owner_id}/'):
        return None
    return path


def download_legacy_profile_object(path: str) -> bytes:
    """Read only from the configured legacy bucket, never via HTTP."""
    if not path.startswith('profiles/'):
        raise PrivateObjectIntegrityError()
    try:
        from hivmeet_backend.firebase_service import firebase_service

        blob = firebase_service.bucket.blob(path)
        blob.reload()
        if int(blob.size or 0) > settings.PROFILE_MEDIA_MAX_UPLOAD_BYTES:
            raise PrivateObjectIntegrityError()
        return blob.download_as_bytes()
    except PrivateObjectIntegrityError:
        raise
    except Exception as exc:
        if exc.__class__.__name__ == 'NotFound':
            raise PrivateObjectNotFound() from None
        raise PrivateStorageUnavailable() from None


def delete_legacy_profile_object(path: str) -> bool:
    """Delete and verify one known legacy object without logging its path."""
    if not path.startswith('profiles/'):
        raise PrivateObjectIntegrityError()
    try:
        from hivmeet_backend.firebase_service import firebase_service

        blob = firebase_service.bucket.blob(path)
        blob.delete()
        return not blob.exists()
    except Exception as exc:
        if exc.__class__.__name__ == 'NotFound':
            return True
        raise PrivateStorageUnavailable() from None


private_object_storage = PrivateObjectStorage()
