# Generated by Django 5.2.4 on 2026-07-25 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_add_interaction_history'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHiddenState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden_at', models.DateTimeField(auto_now_add=True, verbose_name='Hidden at')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_states', to='matching.match', verbose_name='Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_conversations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Hidden conversation',
                'verbose_name_plural': 'Hidden conversations',
                'db_table': 'conversation_hidden_states',
                'indexes': [models.Index(fields=['user', 'match'], name='conversatio_user_id_2bfbec_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'user'), name='unique_hidden_conversation_per_user')],
            },
        ),
    ]
