# Generated by Django 4.2.7 on 2025-12-29 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('super_like', 'Super like'), ('dislike', 'Dislike/Pass')], max_length=20, verbose_name='Interaction type')),
                ('is_revoked', models.BooleanField(default=False, help_text='Whether this interaction has been cancelled by the user', verbose_name='Is revoked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_received', to=settings.AUTH_USER_MODEL, verbose_name='Target user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_sent', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Interaction History',
                'verbose_name_plural': 'Interaction Histories',
                'db_table': 'interaction_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='interaction_user_id_1e6df2_idx'), models.Index(fields=['target_user', '-created_at'], name='interaction_target__8378aa_idx'), models.Index(fields=['interaction_type'], name='interaction_interac_e91966_idx'), models.Index(fields=['user', 'is_revoked'], name='idx_ih_user_revoked'), models.Index(fields=['user', 'interaction_type', 'is_revoked'], name='idx_ih_user_type_revoked')],
            },
        ),
        migrations.AddConstraint(
            model_name='interactionhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_revoked', False)), fields=('user', 'target_user', 'interaction_type'), name='unique_active_interaction'),
        ),
    ]
