# Generated by Django 4.2.7 on 2026-09-22 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def grant_existing_active_matches_full_access(apps, schema_editor):
    """Explicitly preserve all established conversations during rollout."""
    Match = apps.get_model('matching', 'Match')
    Match.objects.filter(status='active').update(access_level='full')


def reverse_grant_existing_active_matches_full_access(apps, schema_editor):
    # Full access is the schema default and remains the safe rollback state.
    return


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0002_add_interaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='access_level',
            field=models.CharField(choices=[('full', 'Full access'), ('free_limited', 'Free limited access'), ('locked', 'Locked monthly Free access')], default='full', max_length=20, verbose_name='Access level'),
        ),
        migrations.AddField(
            model_name='match',
            name='user1_free_messages_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(
            grant_existing_active_matches_full_access,
            reverse_grant_existing_active_matches_full_access,
        ),
        migrations.AddField(
            model_name='match',
            name='user2_free_messages_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MonthlyFreeAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_start', models.DateField()),
                ('purpose', models.CharField(choices=[('like_reveal', 'Received like reveal'), ('free_match', 'Free match unlock')], max_length=20)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('revealed_like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_reveals', to='matching.like')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_free_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monthly_free_accesses',
                'indexes': [models.Index(fields=['user', 'month_start'], name='monthly_fre_user_id_f9fb75_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyfreeaccess',
            constraint=models.UniqueConstraint(fields=('user', 'month_start'), name='unique_monthly_free_access_per_user'),
        ),
    ]
