# Generated by Django 5.2.4 on 2026-07-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('renewal', 'Renewal'), ('refund', 'Refund'), ('modification', 'Modification')], max_length=20, verbose_name='Type'),
        ),
    ]
