# Generated by Django 4.2.7 on 2026-08-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_match', 'Nouveau match'), ('new_message', 'Nouveau message'), ('like', 'Like reçu'), ('super_like', 'Super like reçu'), ('subscription_expiring', 'Abonnement expirant'), ('system', 'Système')], max_length=30, verbose_name='Type'),
        ),
    ]
