# Generated by Django 5.2.4 on 2026-09-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_report_resolved_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_match', 'Nouveau match'), ('new_message', 'Nouveau message'), ('message_read', 'Message read'), ('like', 'Like reçu'), ('super_like', 'Super like reçu'), ('subscription_expiring', 'Abonnement expirant'), ('report_resolved', 'Signalement résolu'), ('system', 'Système')], max_length=30, verbose_name='Type'),
        ),
    ]
